# Generated by Django 4.2.5 on 2024-05-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentapp', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('certificate_file', models.FileField(upload_to='certificates/')),
            ],
        ),
    ]
