# Generated by Django 4.2.5 on 2024-05-14 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercertificate',
            name='certificate_file',
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
