# Generated by Django 4.2.5 on 2024-05-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0002_fullstackvideo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FullstackVideo',
            new_name='F_Video',
        ),
    ]
