# Generated by Django 4.2.5 on 2024-05-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0006_answer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='status',
        ),
    ]
