# Generated by Django 4.2.5 on 2024-05-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0007_remove_answer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Graded', 'Graded')], default='Submitted', max_length=20),
        ),
    ]
