# Generated by Django 4.2.5 on 2024-05-14 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0010_rename_correct_answer_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Quiz_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorapp.question')),
            ],
        ),
    ]
