# Generated by Django 4.2.5 on 2024-05-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0011_remove_question_is_active_alter_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_answer',
            name='is_corrected',
            field=models.BooleanField(default=False),
        ),
    ]
