# Generated by Django 4.2.5 on 2024-05-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0012_quiz_answer_is_corrected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='F_Video',
        ),
    ]
