# Generated by Django 4.2.5 on 2024-05-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0014_quizquestion_remove_quiz_answer_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Full_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
