# Generated by Django 4.2.5 on 2024-05-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0015_full_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Full_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note_file', models.FileField(upload_to='notes/')),
            ],
        ),
    ]
