# Generated by Django 4.2.5 on 2024-05-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0016_full_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='full_note',
            old_name='note_file',
            new_name='file',
        ),
        migrations.AddField(
            model_name='full_note',
            name='content',
            field=models.TextField(default='Default content'),
        ),
        migrations.AlterField(
            model_name='full_note',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
