# Generated by Django 4.2.5 on 2024-05-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0017_rename_note_file_full_note_file_full_note_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='full_note',
            name='content',
        ),
    ]
