# Generated by Django 4.2.5 on 2024-05-18 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0018_remove_full_note_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Full_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('questions', models.TextField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Full_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('answer_file', models.FileField(upload_to='answers/')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Graded', 'Graded')], default='Submitted', max_length=20)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorapp.full_assignment')),
            ],
        ),
    ]
